---
# Configuring a single instance oracle database server

# Creating Oracle directories
- name: Creating Oracle folders
  hosts: "{{ targetgroup }}"
  become: yes
  become_user: root
  become_method: sudo
  #vars:
  #  oracle_version: "{{version}}"
  roles:
    - role: create-oracle-folders

