---
# Deploying new Oracle username

 - name: Create_crdbadmin_group
   group:
     name: "{{crdb_group}}"
     state: present

 - name: Create_cockroach_user
   user:
     name: "{{crdb_user}}"
     state: present     
     append: yes  # adding user to groups
     groups: "{{crdb_group}}"
     update_password: always



