---
# Configuring a single instance oracle database server

# Configuring hosts
- name: configuring host
  hosts: "{{ targetgroup }}"
  become: yes
  become_user: root
  become_method: sudo
  #roles:
  #  - role: configure_host
  tasks:
   - selinux: 
       policy: targeted
       state: permissive 
   - service: 
       name: firewalld 
       state: stopped
       
...