---
# Deploying new Oracle username

 - name: Create_oradmin_group
   group:
     name: oradmin
     state: present

 - name: Create_oradmin_group
   user:
     name: oracle
     state: present     
     append: yes  # adding user to groups
     groups: oracle,oradmin
     update_password: always



