oracle_user: oracle
oracle_dba_group: oradmin
oracle_instal_group: oinstall

grid_user: grid
grid_group: oragrid

# Oracle variables
oracle_base: /opt/ORACLE
oracle_home: "{{oracle_base}}/product/{{oracle_version}}"
grid_home: "{{ oracle_base }}/product/{{grid_version}}"
oracle_inventory: "{{oracle_base}}/oraInventory"
oracle_admin: "{{oracle_base}}/admin"
oracle_tns_admin: "{{oracle_base}}/admin/tnsnames/"
ld_library_path: "{{oracle_home}}/lib"



# Repository variables
local_repo: /opt/ORACLE/SOFT
local_opatch_repo: "{{ local_repo }}/opatch"
local_patch_repo: "{{ local_repo }}/patches"
remote_repo: "{{oracle_base}}/SOFT"
remote_opatch_repo: "{{ remote_repo }}"/opatch
remote_patch_repo: "{{ remote_repo }}"/patches



- oracle_db_versions:
   12201_db_001:
     deprecated: no
     version: 12.2.0.1
     template: db_install_12201.rsp
     installer: "{{oracle_version}}/database"
     opatch: p6880880_122010_Linux-x86-64.zip
     #autopatch:
     #  - 28822515
     #oneoff:
     #  # Duplicate, should be ignored in case of RAC
     #  - 2017-08/26609783
     #  # OJVM
     #  - 2016-10/24433133/24315824