---
# Configuring host for Cockroach installation
# This repo will include all steps to set an Cockroach database server

# Updating repositories
 - name: Updating_Repos
   yum:
      name: '*'
      state: latest
      #exclude: kernel*

# Install required packages 
 - name: Install required packages
   yum:
      name: "{{ cockroach_packages }}"
      state: installed
   with_items:
      "{{cockroach_packages}}"

