---
#
# Playbook for creating Oracle folders
#

# Create Oracle user
- name: deploy_user
  hosts: "{{ targetgroup }}"
  become: yes
  become_user: root
  become_method: sudo
  roles:
   - role: deploy_oracle_user

## Creating Oracle directories
#- name: Creating_Oracle_folders
#  hosts: dbserver
#  become: yes
#  become_user: root
#  become_method: sudo
#  vars:
#    oracle_version: "{{version}}"
#  roles:
#    - role: create_orcl_folder
#
## Create local_repo and copy and unzip Oracle Software.
#- name: Create target software repository
#  hosts: dbserver
#  become: yes
#  become_user: oracle
#  become_method: sudo
#  vars:
#    oracle_version: "{{version}}"
#  roles:
#    - role: copy_soft
