---
#
# Playbook for creating Oracle folders
#
# Create Oracle user
- name: deploy Oracle user
  hosts: "{{ targetgroup }}"
  become: yes
  become_user: root
  become_method: sudo
  roles:
   - role: deploy-oracle-user

# Create Grid user
- name: deploy Grid user
  hosts: "{{ targetgroup }}"
  become: yes
  become_user: root
  become_method: sudo
  roles:
   - role: deploy-grid-user   

# Creating Oracle directories
- name: Creating Oracle folders
  hosts: "{{ targetgroup }}"
  become: yes
  become_user: root
  become_method: sudo
  #vars:
  #  oracle_version: "{{version}}"
  roles:
    - role: create-oracle-folders

# Configuring hosts
- name: configuring host
  hosts: "{{ targetgroup }}"
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - role: configure-host


# Create local_repo and copy and unzip Oracle Software.
- name: Copy Soft
  hosts: "{{ targetgroup }}"
  become: yes
  become_user: oracle
  become_method: sudo
  #vars:
  #  oracle_version: "{{version}}"
  roles:
    - role: copy-soft

# Install Oracle database software at the default location
- name: db_install
  hosts: "{{ targetgroup }}"
  become:  yes
  become_user: oracle
  become_method: sudo
  roles:
    - role: db-install
