---
#
# Playbook for creating Oracle folders
#
# Create Oracle user
- name: deploy_oracle_user
  hosts: "{{ targetgroup }}"
  become: yes
  become_user: root
  become_method: sudo
  roles:
   - role: deploy_oracle_user

# Create Grid user
- name: deploy_oracle_user
  hosts: "{{ targetgroup }}"
  become: yes
  become_user: root
  become_method: sudo
  roles:
   - role: deploy_grid_user   

# Creating Oracle directories
- name: Creating_Oracle_folders
  hosts: "{{ targetgroup }}"
  become: yes
  become_user: root
  become_method: sudo
  #vars:
  #  oracle_version: "{{version}}"
  roles:
    - role: oracle_meta
    - role: create_oracle_folders

# Configuring hosts
- name: configuring host
  hosts: "{{ targetgroup }}"
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - role: configure_host


# Create local_repo and copy and unzip Oracle Software.
- name: Copy_Soft
  hosts: "{{ targetgroup }}"
  become: yes
  become_user: oracle
  become_method: sudo
  #vars:
  #  oracle_version: "{{version}}"
  roles:
    - role: oracle_meta
    - role: copy_soft

# Install Oracle database software at the default location
- name: db_install
  hosts: "{{ targetgroup }}"
  become:  yes
  become_user: oracle
  become_method: sudo
  roles:
    - role: db_install
