---
- name: Set authorized key taken from control host
  hosts: "{{ targetgroup }}"
   #become: yes
   #become_user: root
   #become_method: sudo
   #ssh: 
  ansible_ssh_user: root
  ansible_ssh_pass: "{{ ansible_root_pass }}"
  
  roles:
   - manage_passwordless
