---
  # tasks for creating folders
  #- name: create_cockroach_target_repository
  #      
  #  file: dest="{{target_repo}}/DB" state=directory owner="{{ crdb_user }}" group="{{ crdb_group }}"
 #- name: create_software_repository
 #  file: dest="{{ remote_repo }}" state=directory owner="{{ crdb_user }}" group="{{ crdb_group }}"    
 
 - name: create_cockroach_home
   file: dest="{{ crdb_home }}" state=directory owner="{{ crdb_user }}" group="{{ crdb_group }}"

 - name: create_cockroach_data
   file: dest="{{ crdb_data }}" state=directory owner="{{ crdb_user }}" group="{{ crdb_group }}"
   
